language: node_js
node_js:
  - 14
script:
  - npm install eslint --save-dev
  - npm install --save-dev stylelint stylelint-config-standard
  - npm install eslint@4.x babel-eslint@8 --save-dev
  - eslint "js/*.js" --ignore-pattern node_modules/
  - npx stylelint "css/*.css"
